//! Block tag registry loaded from vanilla tag data at compile time.
//!
//! Tags group blocks into categories for behavior dispatch.
//! Membership testing is O(log n) via binary search on tag name,
//! then O(log m) via binary search on block type ID within the tag.
//!
//! Vanilla tags are loaded from `tags.json` (produced by `bundle_tags.py`).
//! Custom Oxidized tags are loaded from `src/data/tags/block/*.json`.
//! Both are resolved to block type IDs at compile time by `build.rs`.

mod generated {
    include!(concat!(env!("OUT_DIR"), "/block_tags_generated.rs"));
}

/// Zero-sized handle to the compile-time block tag registry.
///
/// All tag data is stored in static arrays generated by `build.rs`.
/// This struct provides the query API.
///
/// # Examples
///
/// ```
/// use oxidized_world::registry::BlockTags;
///
/// let tags = BlockTags;
/// // Check if block type 220 (oak_door) is in the doors tag
/// assert!(tags.contains("minecraft:doors", 220));
/// assert!(!tags.contains("minecraft:doors", 1));
/// ```
pub struct BlockTags;

/// A sorted slice of block type IDs belonging to a single tag.
///
/// Membership testing is O(log n) via binary search.
#[derive(Debug, Clone, Copy)]
pub struct TagSet {
    members: &'static [u16],
}

impl TagSet {
    /// Returns `true` if this tag contains the given block type ID.
    #[inline]
    pub fn contains(&self, block_type_id: u16) -> bool {
        self.members.binary_search(&block_type_id).is_ok()
    }

    /// Returns the number of block types in this tag.
    #[inline]
    pub fn len(&self) -> usize {
        self.members.len()
    }

    /// Returns `true` if this tag has no members.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.members.is_empty()
    }

    /// Returns an iterator over the block type IDs in this tag.
    #[inline]
    pub fn iter(&self) -> impl Iterator<Item = u16> + '_ {
        self.members.iter().copied()
    }
}

impl BlockTags {
    /// Returns `true` if the given block type ID belongs to the named tag.
    ///
    /// Returns `false` if the tag name is unknown or the block is not a member.
    ///
    /// # Examples
    ///
    /// ```
    /// use oxidized_world::registry::BlockTags;
    ///
    /// let tags = BlockTags;
    /// assert!(tags.contains("minecraft:doors", 220));
    /// assert!(!tags.contains("nonexistent:tag", 0));
    /// ```
    #[inline]
    pub fn contains(&self, tag: &str, block_type_id: u16) -> bool {
        self.get(tag)
            .map_or(false, |set| set.contains(block_type_id))
    }

    /// Returns the [`TagSet`] for the given tag name, or `None` if unknown.
    ///
    /// # Examples
    ///
    /// ```
    /// use oxidized_world::registry::BlockTags;
    ///
    /// let tags = BlockTags;
    /// let doors = tags.get("minecraft:doors").unwrap();
    /// assert!(!doors.is_empty());
    /// ```
    pub fn get(&self, tag: &str) -> Option<TagSet> {
        let idx = generated::TAG_NAMES
            .binary_search(&tag)
            .ok()?;
        let (start, len) = generated::TAG_RANGES[idx];
        let start = start as usize;
        let end = start + len as usize;
        Some(TagSet {
            members: &generated::TAG_MEMBERS[start..end],
        })
    }

    /// Returns the total number of tags in the registry.
    #[inline]
    pub fn tag_count(&self) -> usize {
        generated::TAG_NAMES.len()
    }

    /// Returns an iterator over all tag names in sorted order.
    #[inline]
    pub fn tag_names(&self) -> impl Iterator<Item = &'static str> {
        generated::TAG_NAMES.iter().copied()
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn test_tag_count_is_positive() {
        let tags = BlockTags;
        assert!(tags.tag_count() > 0, "should have at least one tag");
    }

    #[test]
    fn test_vanilla_doors_tag_exists() {
        let tags = BlockTags;
        let doors = tags.get("minecraft:doors");
        assert!(doors.is_some(), "minecraft:doors tag should exist");
        let doors = doors.unwrap();
        assert!(!doors.is_empty(), "doors tag should have members");
    }

    #[test]
    fn test_vanilla_doors_contains_oak_door() {
        let tags = BlockTags;
        // oak_door should be in the doors tag
        let doors = tags.get("minecraft:doors").unwrap();
        // Find oak_door type ID
        let oak_door_id = crate::registry::BlockRegistry
            .get_block_def("minecraft:oak_door")
            .expect("oak_door should exist in registry");
        let type_id = oak_door_id.first_state;
        let block_type = crate::registry::generated::BLOCK_STATE_DATA[type_id as usize].block_type;
        assert!(
            doors.contains(block_type),
            "oak_door (type {block_type}) should be in minecraft:doors"
        );
    }

    #[test]
    fn test_vanilla_doors_does_not_contain_stone() {
        let tags = BlockTags;
        let stone_def = crate::registry::BlockRegistry
            .get_block_def("minecraft:stone")
            .expect("stone should exist");
        let block_type =
            crate::registry::generated::BLOCK_STATE_DATA[stone_def.first_state as usize]
                .block_type;
        assert!(
            !tags.contains("minecraft:doors", block_type),
            "stone should not be in minecraft:doors"
        );
    }

    #[test]
    fn test_unknown_tag_returns_none() {
        let tags = BlockTags;
        assert!(tags.get("nonexistent:tag").is_none());
    }

    #[test]
    fn test_unknown_tag_contains_returns_false() {
        let tags = BlockTags;
        assert!(!tags.contains("nonexistent:tag", 0));
    }

    #[test]
    fn test_vanilla_beds_tag() {
        let tags = BlockTags;
        let beds = tags.get("minecraft:beds").expect("beds tag should exist");
        assert_eq!(beds.len(), 16, "should have 16 bed colors");
    }

    #[test]
    fn test_vanilla_replaceable_tag() {
        let tags = BlockTags;
        let replaceable = tags
            .get("minecraft:replaceable")
            .expect("replaceable tag should exist");
        // air (type 0) should be replaceable
        assert!(
            replaceable.contains(0),
            "air (type 0) should be replaceable"
        );
    }

    #[test]
    fn test_vanilla_buttons_tag() {
        let tags = BlockTags;
        let buttons = tags
            .get("minecraft:buttons")
            .expect("buttons tag should exist");
        assert!(buttons.len() >= 10, "should have many button types");
    }

    #[test]
    fn test_custom_tall_plants_tag() {
        let tags = BlockTags;
        let tall_plants = tags
            .get("oxidized:tall_plants")
            .expect("oxidized:tall_plants tag should exist");
        assert_eq!(tall_plants.len(), 8, "should have 8 tall plants");

        // Verify sunflower is in the tag
        let sunflower_def = crate::registry::BlockRegistry
            .get_block_def("minecraft:sunflower")
            .expect("sunflower should exist");
        let block_type =
            crate::registry::generated::BLOCK_STATE_DATA[sunflower_def.first_state as usize]
                .block_type;
        assert!(
            tall_plants.contains(block_type),
            "sunflower should be in oxidized:tall_plants"
        );
    }

    #[test]
    fn test_custom_wall_mountable_tag() {
        let tags = BlockTags;
        let wall_mountable = tags
            .get("oxidized:wall_mountable")
            .expect("oxidized:wall_mountable tag should exist");
        assert!(
            wall_mountable.len() >= 50,
            "should have many wall-mountable blocks"
        );
    }

    #[test]
    fn test_custom_player_direction_tag() {
        let tags = BlockTags;
        let player_dir = tags
            .get("oxidized:player_direction")
            .expect("oxidized:player_direction tag should exist");
        assert!(
            player_dir.len() >= 100,
            "should have many player-direction blocks"
        );
    }

    #[test]
    fn test_custom_interactable_tag() {
        let tags = BlockTags;
        let interactable = tags
            .get("oxidized:interactable")
            .expect("oxidized:interactable tag should exist");

        // crafting_table should be in the interactable tag
        let ct_def = crate::registry::BlockRegistry
            .get_block_def("minecraft:crafting_table")
            .expect("crafting_table should exist");
        let block_type =
            crate::registry::generated::BLOCK_STATE_DATA[ct_def.first_state as usize].block_type;
        assert!(
            interactable.contains(block_type),
            "crafting_table should be in oxidized:interactable"
        );
    }

    #[test]
    fn test_tag_names_are_sorted() {
        let tags = BlockTags;
        let names: Vec<_> = tags.tag_names().collect();
        let mut sorted = names.clone();
        sorted.sort();
        assert_eq!(names, sorted, "tag names should be in sorted order");
    }

    #[test]
    fn test_tag_members_are_sorted() {
        let tags = BlockTags;
        for name in tags.tag_names() {
            let set = tags.get(name).unwrap();
            let members: Vec<_> = set.iter().collect();
            let mut sorted = members.clone();
            sorted.sort();
            assert_eq!(
                members, sorted,
                "members of tag {name} should be sorted"
            );
        }
    }

    #[test]
    fn test_all_signs_tag() {
        let tags = BlockTags;
        let signs = tags
            .get("minecraft:all_signs")
            .expect("all_signs tag should exist");
        assert_eq!(signs.len(), 48, "should have 48 sign variants");
    }

    #[test]
    fn test_tag_set_iter() {
        let tags = BlockTags;
        let air = tags.get("minecraft:air").expect("air tag should exist");
        let members: Vec<u16> = air.iter().collect();
        assert_eq!(members.len(), air.len());
        assert_eq!(members.len(), 3, "air tag should have 3 members");
    }
}
