//! Server configuration loaded from `oxidized.toml`.
//!
//! Uses TOML format with serde derives for type-safe deserialization.
//! See [ADR-033](../../../docs/adr/adr-033-configuration-format.md) for rationale.

mod admin;
mod advanced;
mod display;
mod error;
mod gameplay;
mod network;
mod world;

pub use admin::{AdminConfig, QueryConfig, RconConfig};
pub use advanced::{AdvancedConfig, ManagementConfig, PacksConfig, ResourcePackConfig};
pub use display::{ChatConfig, DisplayConfig};
pub use error::ConfigError;
pub use gameplay::GameplayConfig;
pub use network::NetworkConfig;
pub use world::WorldConfig;

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use anyhow::Context;
use serde::{Deserialize, Serialize};

/// Server configuration loaded from `oxidized.toml`.
///
/// All default values match the vanilla Minecraft 26.1-pre-3 server
/// (with Oxidized-specific branding for the MOTD).
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
#[serde(default)]
pub struct ServerConfig {
    /// Network-related settings.
    pub network: NetworkConfig,
    /// Gameplay-related settings.
    pub gameplay: GameplayConfig,
    /// World generation and storage settings.
    pub world: WorldConfig,
    /// Display and MOTD settings.
    pub display: DisplayConfig,
    /// Chat formatting settings.
    pub chat: ChatConfig,
    /// Admin and security settings.
    pub admin: AdminConfig,
    /// RCON remote console settings.
    pub rcon: RconConfig,
    /// GameSpy4 query protocol settings.
    pub query: QueryConfig,
    /// Server resource pack settings.
    pub resource_pack: ResourcePackConfig,
    /// Management server settings.
    pub management: ManagementConfig,
    /// Data pack settings.
    pub packs: PacksConfig,
    /// Advanced / diagnostic settings.
    pub advanced: AdvancedConfig,
    /// Unknown/future keys preserved for forward compatibility.
    #[serde(flatten)]
    pub extra: BTreeMap<String, toml::Value>,
}

impl ServerConfig {
    /// Loads configuration from a TOML file, or creates a default if the file doesn't exist.
    ///
    /// # Errors
    ///
    /// Returns an error if the file exists but cannot be read or parsed.
    pub fn load_or_create(path: &Path) -> anyhow::Result<Self> {
        if path.exists() {
            let content = fs::read_to_string(path)
                .with_context(|| format!("failed to read {}", path.display()))?;
            let config: Self = toml::from_str(&content)
                .with_context(|| format!("failed to parse {}", path.display()))?;
            Ok(config)
        } else {
            let config = Self::default();
            config.save(path)?;
            Ok(config)
        }
    }

    /// Saves the configuration to a TOML file.
    ///
    /// # Errors
    ///
    /// Returns an error if the file cannot be written.
    pub fn save(&self, path: &Path) -> anyhow::Result<()> {
        let content = toml::to_string_pretty(self).context("failed to serialize configuration")?;
        let output = format!(
            "# Oxidized Minecraft Server Configuration\n\
             # Generated by Oxidized v{}\n\
             # See https://github.com/dodoflix/Oxidized for documentation\n\n{}",
            env!("CARGO_PKG_VERSION"),
            content
        );
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).with_context(|| {
                format!("failed to create parent directories for {}", path.display())
            })?;
        }
        fs::write(path, output).with_context(|| format!("failed to write {}", path.display()))?;
        Ok(())
    }

    /// Validates all config values are within acceptable ranges.
    ///
    /// # Errors
    ///
    /// Returns a [`ConfigError`] describing the first invalid value found.
    pub fn validate(&self) -> Result<(), ConfigError> {
        if self.network.port == 0 {
            return Err(ConfigError::InvalidPort(self.network.port));
        }
        if self.rcon.port == 0 && self.rcon.enabled {
            return Err(ConfigError::InvalidPort(self.rcon.port));
        }
        if self.query.port == 0 && self.query.enabled {
            return Err(ConfigError::InvalidPort(self.query.port));
        }
        if !(2..=32).contains(&self.world.view_distance) {
            return Err(ConfigError::InvalidViewDistance(self.world.view_distance));
        }
        if !(2..=32).contains(&self.world.simulation_distance) {
            return Err(ConfigError::InvalidSimulationDistance(
                self.world.simulation_distance,
            ));
        }
        if self.gameplay.max_players == 0 {
            return Err(ConfigError::InvalidMaxPlayers(self.gameplay.max_players));
        }
        // color_char must be empty (disabled) or a single non-alphanumeric ASCII char
        if !self.chat.color_char.is_empty() {
            let chars: Vec<char> = self.chat.color_char.chars().collect();
            if chars.len() != 1 || !chars[0].is_ascii() || chars[0].is_ascii_alphanumeric() {
                return Err(ConfigError::InvalidColorChar(self.chat.color_char.clone()));
            }
        }
        Ok(())
    }
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::needless_pass_by_value,
    clippy::panic
)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    #[test]
    fn test_default_config_serializes_to_valid_toml() {
        let config = ServerConfig::default();
        let toml_str =
            toml::to_string_pretty(&config).expect("default config should serialize to TOML");
        let deserialized: ServerConfig =
            toml::from_str(&toml_str).expect("serialized TOML should deserialize back");
        assert_eq!(config, deserialized);
    }

    #[test]
    fn test_load_or_create_creates_default_file() {
        let dir = tempfile::tempdir().expect("should create tempdir");
        let path = dir.path().join("oxidized.toml");

        assert!(!path.exists());

        let config = ServerConfig::load_or_create(&path).expect("should create default");
        assert!(path.exists());
        assert_eq!(config, ServerConfig::default());

        // Verify the file contains TOML content.
        let contents = fs::read_to_string(&path).expect("should read");
        assert!(contents.contains("[network]"));
        assert!(contents.contains("[gameplay]"));
    }

    #[test]
    fn test_validate_accepts_valid_defaults() {
        let config = ServerConfig::default();
        assert!(config.validate().is_ok());
    }

    #[test]
    fn test_validate_rejects_invalid_port() {
        let mut config = ServerConfig::default();
        config.network.port = 0;
        let err = config.validate().unwrap_err();
        assert!(matches!(err, ConfigError::InvalidPort(0)));
    }

    #[test]
    fn test_validate_rejects_invalid_view_distance() {
        let mut config = ServerConfig::default();

        config.world.view_distance = 1;
        let err = config.validate().unwrap_err();
        assert!(matches!(err, ConfigError::InvalidViewDistance(1)));

        config.world.view_distance = 33;
        let err = config.validate().unwrap_err();
        assert!(matches!(err, ConfigError::InvalidViewDistance(33)));
    }

    #[test]
    fn test_validate_rejects_invalid_simulation_distance() {
        let mut config = ServerConfig::default();

        config.world.simulation_distance = 1;
        let err = config.validate().unwrap_err();
        assert!(matches!(err, ConfigError::InvalidSimulationDistance(1)));

        config.world.simulation_distance = 33;
        let err = config.validate().unwrap_err();
        assert!(matches!(err, ConfigError::InvalidSimulationDistance(33)));
    }

    #[test]
    fn test_validate_rejects_invalid_max_players() {
        let mut config = ServerConfig::default();
        config.gameplay.max_players = 0;
        let err = config.validate().unwrap_err();
        assert!(matches!(err, ConfigError::InvalidMaxPlayers(0)));
    }

    #[test]
    fn test_roundtrip_preserves_all_fields() {
        let dir = tempfile::tempdir().expect("should create tempdir");
        let path = dir.path().join("oxidized.toml");

        let config = ServerConfig {
            network: NetworkConfig {
                port: 19132,
                ip: "192.168.1.1".to_string(),
                online_mode: false,
                prevent_proxy_connections: true,
                compression_threshold: 512,
                use_native_transport: false,
                rate_limit: 10,
                accepts_transfers: true,
            },
            gameplay: GameplayConfig {
                gamemode: "creative".to_string(),
                difficulty: "hard".to_string(),
                hardcore: true,
                force_gamemode: true,
                max_players: 100,
                spawn_protection: 32,
                max_world_size: 10000,
                allow_flight: true,
                spawn_npcs: false,
                spawn_animals: false,
                spawn_monsters: false,
                allow_nether: false,
                max_chained_neighbor_updates: 500_000,
                pvp: false,
            },
            world: WorldConfig {
                name: "custom_world".to_string(),
                seed: "12345".to_string(),
                generate_structures: false,
                view_distance: 16,
                simulation_distance: 8,
                sync_chunk_writes: false,
                region_file_compression: "none".to_string(),
            },
            display: DisplayConfig {
                motd: "Full Roundtrip Test".to_string(),
                enable_status: false,
                hide_online_players: true,
                entity_broadcast_range_percentage: 200,
                status_heartbeat_interval: 15,
            },
            chat: ChatConfig {
                color_char: "&".to_string(),
            },
            admin: AdminConfig {
                white_list: true,
                enforce_whitelist: true,
                op_permission_level: 3,
                function_permission_level: 3,
                enforce_secure_profile: false,
                log_ips: false,
                max_tick_time: 120_000,
                player_idle_timeout: 30,
                broadcast_console_to_ops: false,
                broadcast_rcon_to_ops: false,
                pause_when_empty_seconds: 120,
            },
            rcon: RconConfig {
                enabled: true,
                port: 25576,
                password: "secret123".to_string(),
            },
            query: QueryConfig {
                enabled: true,
                port: 25566,
            },
            resource_pack: ResourcePackConfig {
                url: "https://example.com/pack.zip".to_string(),
                sha1: "abc123def456".to_string(),
                prompt: "Please install".to_string(),
                required: true,
            },
            management: ManagementConfig {
                enabled: true,
                host: "mgmt.example.com".to_string(),
                port: 8443,
                secret: "mgmt-secret".to_string(),
                tls_enabled: true,
            },
            packs: PacksConfig {
                initial_enabled: "vanilla,fabric".to_string(),
                initial_disabled: "experimental".to_string(),
            },
            advanced: AdvancedConfig {
                enable_jmx_monitoring: true,
                text_filtering_config: "filter.json".to_string(),
                text_filtering_version: 2,
                enable_code_of_conduct: true,
                bug_report_link: "https://bugs.example.com".to_string(),
            },
            extra: BTreeMap::new(),
        };

        config.save(&path).expect("save should succeed");
        let loaded = ServerConfig::load_or_create(&path).expect("load should succeed");
        assert_eq!(config, loaded);
    }

    // -----------------------------------------------------------------------
    // Property-based tests (proptest)
    // -----------------------------------------------------------------------

    proptest! {
        #[test]
        fn test_roundtrip_invariant_for_network_config(
            port in 1u16..=65535u16,
            online_mode in proptest::bool::ANY,
            compression in -1i32..1024i32,
            rate_limit in 0i32..1000i32,
        ) {
            let mut config = ServerConfig::default();
            config.network.port = port;
            config.network.online_mode = online_mode;
            config.network.compression_threshold = compression;
            config.network.rate_limit = rate_limit;

            let toml_str = toml::to_string_pretty(&config).unwrap();
            let loaded: ServerConfig = toml::from_str(&toml_str).unwrap();

            assert_eq!(config.network.port, loaded.network.port);
            assert_eq!(config.network.online_mode, loaded.network.online_mode);
            assert_eq!(
                config.network.compression_threshold,
                loaded.network.compression_threshold
            );
            assert_eq!(config.network.rate_limit, loaded.network.rate_limit);
        }
    }

    proptest! {
        #[test]
        fn test_roundtrip_invariant_for_gameplay_config(
            max_players in 1u32..1000u32,
            view_distance in 2u32..=32u32,
            simulation_distance in 2u32..=32u32,
            hardcore in proptest::bool::ANY,
            spawn_protection in 0u32..100u32,
        ) {
            let mut config = ServerConfig::default();
            config.gameplay.max_players = max_players;
            config.world.view_distance = view_distance;
            config.world.simulation_distance = simulation_distance;
            config.gameplay.hardcore = hardcore;
            config.gameplay.spawn_protection = spawn_protection;

            let toml_str = toml::to_string_pretty(&config).unwrap();
            let loaded: ServerConfig = toml::from_str(&toml_str).unwrap();

            assert_eq!(config.gameplay.max_players, loaded.gameplay.max_players);
            assert_eq!(config.world.view_distance, loaded.world.view_distance);
            assert_eq!(
                config.world.simulation_distance,
                loaded.world.simulation_distance
            );
            assert_eq!(config.gameplay.hardcore, loaded.gameplay.hardcore);
            assert_eq!(
                config.gameplay.spawn_protection,
                loaded.gameplay.spawn_protection
            );
        }
    }

    proptest! {
        #[test]
        fn test_roundtrip_invariant_for_string_fields(
            motd in "[a-zA-Z0-9 ]{0,50}",
            world_name in "[a-zA-Z0-9_]{1,30}",
            seed in "[a-zA-Z0-9]{0,20}",
        ) {
            let mut config = ServerConfig::default();
            config.display.motd = motd.clone();
            config.world.name = world_name.clone();
            config.world.seed = seed.clone();

            let toml_str = toml::to_string_pretty(&config).unwrap();
            let loaded: ServerConfig = toml::from_str(&toml_str).unwrap();

            assert_eq!(motd, loaded.display.motd);
            assert_eq!(world_name, loaded.world.name);
            assert_eq!(seed, loaded.world.seed);
        }
    }

    // -----------------------------------------------------------------------
    // Snapshot test (insta)
    // -----------------------------------------------------------------------

    #[test]
    fn test_default_config_snapshot() {
        let config = ServerConfig::default();
        let toml_str = toml::to_string_pretty(&config).unwrap();
        insta::assert_snapshot!(toml_str);
    }

    // -----------------------------------------------------------------------
    // Boundary validation tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_validate_port_accepts_boundary_values() {
        let mut config = ServerConfig::default();
        config.network.port = 1;
        assert!(config.validate().is_ok(), "port 1 should be valid");

        config.network.port = 65535;
        assert!(config.validate().is_ok(), "port 65535 should be valid");
    }

    #[test]
    fn test_validate_view_distance_accepts_boundary_values() {
        let mut config = ServerConfig::default();
        config.world.view_distance = 2;
        assert!(config.validate().is_ok(), "view_distance 2 should be valid");

        config.world.view_distance = 32;
        assert!(
            config.validate().is_ok(),
            "view_distance 32 should be valid"
        );
    }

    #[test]
    fn test_validate_simulation_distance_accepts_boundary_values() {
        let mut config = ServerConfig::default();
        config.world.simulation_distance = 2;
        assert!(config.validate().is_ok(), "sim_distance 2 should be valid");

        config.world.simulation_distance = 32;
        assert!(config.validate().is_ok(), "sim_distance 32 should be valid");
    }

    #[test]
    fn test_validate_rejects_rcon_port_zero_when_enabled() {
        let mut config = ServerConfig::default();
        config.rcon.enabled = true;
        config.rcon.port = 0;
        assert!(
            matches!(config.validate(), Err(ConfigError::InvalidPort(0))),
            "rcon port 0 with enabled=true should fail"
        );
    }

    #[test]
    fn test_validate_allows_rcon_port_zero_when_disabled() {
        let mut config = ServerConfig::default();
        config.rcon.enabled = false;
        config.rcon.port = 0;
        assert!(
            config.validate().is_ok(),
            "rcon port 0 with enabled=false should be ok"
        );
    }

    #[test]
    fn test_validate_rejects_query_port_zero_when_enabled() {
        let mut config = ServerConfig::default();
        config.query.enabled = true;
        config.query.port = 0;
        assert!(
            matches!(config.validate(), Err(ConfigError::InvalidPort(0))),
            "query port 0 with enabled=true should fail"
        );
    }

    #[test]
    fn test_validate_allows_query_port_zero_when_disabled() {
        let mut config = ServerConfig::default();
        config.query.enabled = false;
        config.query.port = 0;
        assert!(
            config.validate().is_ok(),
            "query port 0 with enabled=false should be ok"
        );
    }

    // -----------------------------------------------------------------------
    // Partial TOML tests (missing sections get defaults)
    // -----------------------------------------------------------------------

    #[test]
    fn test_partial_toml_gets_defaults_for_missing_sections() {
        let partial = r#"
[network]
port = 19132
"#;
        let config: ServerConfig = toml::from_str(partial).unwrap();
        assert_eq!(config.network.port, 19132);
        // All other sections should be defaults
        assert_eq!(config.gameplay.max_players, 20);
        assert_eq!(config.world.name, "world");
        assert_eq!(config.display.motd, "An Oxidized Minecraft Server");
        assert!(!config.rcon.enabled);
    }

    #[test]
    fn test_empty_toml_produces_all_defaults() {
        let config: ServerConfig = toml::from_str("").unwrap();
        let default = ServerConfig::default();
        assert_eq!(config, default);
    }

    #[test]
    fn test_unknown_keys_are_preserved_through_roundtrip() {
        let input = r#"
[network]
port = 25565

[unknown_section]
key = "value"
"#;
        let config: ServerConfig = toml::from_str(input).unwrap();
        assert_eq!(config.network.port, 25565);
        // Unknown top-level section is captured in the `extra` map
        assert!(
            config.extra.contains_key("unknown_section"),
            "unknown sections should be preserved in extra"
        );

        // Roundtrip: serialize back and re-parse
        let serialized = toml::to_string_pretty(&config).unwrap();
        let reloaded: ServerConfig = toml::from_str(&serialized).unwrap();
        assert!(
            reloaded.extra.contains_key("unknown_section"),
            "unknown sections should survive roundtrip"
        );
    }

    // -----------------------------------------------------------------------
    // TOML format edge cases
    // -----------------------------------------------------------------------

    #[test]
    fn test_toml_with_inline_comments_parses_correctly() {
        let input = r#"
# Server configuration
[network]
port = 25565 # Standard MC port
online_mode = true
"#;
        let config: ServerConfig = toml::from_str(input).unwrap();
        assert_eq!(config.network.port, 25565);
        assert!(config.network.online_mode);
    }

    #[test]
    fn test_toml_with_extra_whitespace_parses_correctly() {
        let input = r#"
[network]
port   =   19132
online_mode   =   false
"#;
        let config: ServerConfig = toml::from_str(input).unwrap();
        assert_eq!(config.network.port, 19132);
        assert!(!config.network.online_mode);
    }

    // -----------------------------------------------------------------------
    // File I/O integration tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_save_and_reload_produces_identical_config() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("oxidized.toml");

        let mut config = ServerConfig::default();
        config.network.port = 19132;
        config.gameplay.max_players = 100;
        config.display.motd = "Test Server".to_string();
        config.rcon.enabled = true;
        config.rcon.password = "secret".to_string();

        config.save(&path).unwrap();
        let loaded = ServerConfig::load_or_create(&path).unwrap();

        assert_eq!(config, loaded);
    }

    #[test]
    fn test_saved_file_starts_with_header_comment() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("oxidized.toml");

        let config = ServerConfig::default();
        config.save(&path).unwrap();

        let content = fs::read_to_string(&path).unwrap();
        assert!(
            content.starts_with("# Oxidized"),
            "file should start with header comment"
        );
    }

    // -----------------------------------------------------------------------
    // Security — secret redaction in Debug output
    // -----------------------------------------------------------------------

    #[test]
    fn test_debug_redacts_rcon_password() {
        let rcon = RconConfig {
            password: "super_secret_password".to_string(),
            ..RconConfig::default()
        };
        let debug_output = format!("{:?}", rcon);
        assert!(
            !debug_output.contains("super_secret_password"),
            "Debug output must not contain the actual password"
        );
        assert!(
            debug_output.contains("[REDACTED]"),
            "Debug output should show [REDACTED]"
        );
    }

    #[test]
    fn test_debug_redacts_management_secret() {
        let mgmt = ManagementConfig {
            secret: "top_secret_key".to_string(),
            ..ManagementConfig::default()
        };
        let debug_output = format!("{:?}", mgmt);
        assert!(
            !debug_output.contains("top_secret_key"),
            "Debug output must not contain the actual secret"
        );
        assert!(
            debug_output.contains("[REDACTED]"),
            "Debug output should show [REDACTED]"
        );
    }

    // ── ChatConfig / color_char validation ───────────────────────────

    #[test]
    fn test_color_char_default_is_ampersand() {
        let chat = ChatConfig::default();
        assert_eq!(chat.color_char, "&");
        assert_eq!(chat.color_char(), Some('&'));
    }

    #[test]
    fn test_color_char_empty_means_disabled() {
        let chat = ChatConfig {
            color_char: String::new(),
        };
        assert_eq!(chat.color_char(), None);
    }

    #[test]
    fn test_color_char_valid_symbols() {
        for ch in ['&', '#', '!', '@', '$', '%', '^', '~'] {
            let mut cfg = ServerConfig::default();
            cfg.chat.color_char = ch.to_string();
            cfg.validate()
                .unwrap_or_else(|e| panic!("'{ch}' should be valid: {e}"));
        }
    }

    #[test]
    fn test_color_char_rejects_alphanumeric() {
        for ch in ['a', 'Z', '0', '9'] {
            let mut cfg = ServerConfig::default();
            cfg.chat.color_char = ch.to_string();
            assert!(cfg.validate().is_err(), "'{ch}' should be rejected");
        }
    }

    #[test]
    fn test_color_char_rejects_multi_char() {
        let mut cfg = ServerConfig::default();
        cfg.chat.color_char = "&&".to_string();
        assert!(cfg.validate().is_err(), "multi-char should be rejected");
    }

    #[test]
    fn test_color_char_rejects_non_ascii() {
        let mut cfg = ServerConfig::default();
        cfg.chat.color_char = "§".to_string();
        assert!(cfg.validate().is_err(), "non-ASCII should be rejected");
    }

    #[test]
    fn test_color_char_empty_passes_validation() {
        let mut cfg = ServerConfig::default();
        cfg.chat.color_char = String::new();
        cfg.validate().unwrap();
    }
}
