//! Server configuration loaded from `oxidized.toml`.
//!
//! Uses TOML format with serde derives for type-safe deserialization.
//! See ADR-033 (Configuration Format) for rationale.

mod admin;
mod advanced;
mod display;
mod error;
mod gameplay;
mod network;
mod world;

pub use admin::{AdminConfig, QueryConfig, RconConfig};
pub use advanced::{AdvancedConfig, ManagementConfig, PacksConfig, ResourcePackConfig};
pub use display::{ChatConfig, DisplayConfig};
pub use error::ConfigError;
pub use gameplay::{EntityTrackingConfig, GameplayConfig, WeatherConfig};
pub use network::{NetworkConfig, NetworkTimeoutsConfig, RateLimitConfig};
pub use world::WorldConfig;

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use anyhow::Context;
use serde::{Deserialize, Serialize};
use tracing::{info, warn};

/// Server configuration loaded from `oxidized.toml`.
///
/// All default values match the vanilla Minecraft 26.1 server
/// (with Oxidized-specific branding for the MOTD).
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
#[serde(default)]
pub struct ServerConfig {
    /// Network-related settings.
    pub network: NetworkConfig,
    /// Gameplay-related settings.
    pub gameplay: GameplayConfig,
    /// World generation and storage settings.
    pub world: WorldConfig,
    /// Display and MOTD settings.
    pub display: DisplayConfig,
    /// Chat formatting settings.
    pub chat: ChatConfig,
    /// Admin and security settings.
    pub admin: AdminConfig,
    /// RCON remote console settings.
    pub rcon: RconConfig,
    /// GameSpy4 query protocol settings.
    pub query: QueryConfig,
    /// Server resource pack settings.
    pub resource_pack: ResourcePackConfig,
    /// Management server settings.
    pub management: ManagementConfig,
    /// Data pack settings.
    pub packs: PacksConfig,
    /// Advanced / diagnostic settings.
    pub advanced: AdvancedConfig,
    /// Unknown/future keys preserved for forward compatibility.
    #[serde(flatten)]
    pub extra: BTreeMap<String, toml::Value>,
}

impl ServerConfig {
    /// Loads configuration from a TOML file, or creates a default if the file doesn't exist.
    ///
    /// # Errors
    ///
    /// Returns an error if the file exists but cannot be read or parsed.
    pub fn load_or_create(path: &Path) -> anyhow::Result<Self> {
        if path.exists() {
            let content = fs::read_to_string(path)
                .with_context(|| format!("failed to read {}", path.display()))?;
            let config: Self = toml::from_str(&content)
                .with_context(|| format!("failed to parse {}", path.display()))?;
            Ok(config)
        } else {
            let config = Self::default();
            config.save(path)?;
            Ok(config)
        }
    }

    /// Saves the configuration to a TOML file.
    ///
    /// # Errors
    ///
    /// Returns an error if the file cannot be written.
    pub fn save(&self, path: &Path) -> anyhow::Result<()> {
        let content = toml::to_string_pretty(self).context("failed to serialize configuration")?;
        let output = format!(
            "# Oxidized Minecraft Server Configuration\n\
             # Generated by Oxidized v{}\n\
             # See https://github.com/oxidized-mc/server for documentation\n\
             #\n\
             # Environment variables override file values.\n\
             # Format: OXIDIZED_{{SECTION}}_{{FIELD}}=value\n\
             # Example: OXIDIZED_NETWORK_PORT=25566\n\n{}",
            env!("CARGO_PKG_VERSION"),
            content
        );
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).with_context(|| {
                format!("failed to create parent directories for {}", path.display())
            })?;
        }
        fs::write(path, output).with_context(|| format!("failed to write {}", path.display()))?;
        Ok(())
    }

    /// Validates all config values are within acceptable ranges.
    ///
    /// # Errors
    ///
    /// Returns a [`ConfigError`] describing the first invalid value found.
    pub fn validate(&self) -> Result<(), ConfigError> {
        if self.network.port == 0 {
            return Err(ConfigError::InvalidPort(self.network.port));
        }
        if self.rcon.port == 0 && self.rcon.is_enabled {
            return Err(ConfigError::InvalidPort(self.rcon.port));
        }
        if self.query.port == 0 && self.query.is_enabled {
            return Err(ConfigError::InvalidPort(self.query.port));
        }
        if !(2..=32).contains(&self.world.view_distance) {
            return Err(ConfigError::InvalidViewDistance(self.world.view_distance));
        }
        if !(2..=32).contains(&self.world.simulation_distance) {
            return Err(ConfigError::InvalidSimulationDistance(
                self.world.simulation_distance,
            ));
        }
        if self.gameplay.max_players == 0 {
            return Err(ConfigError::InvalidMaxPlayers(self.gameplay.max_players));
        }
        // color_char must be empty (disabled) or a single non-alphanumeric ASCII char
        if !self.chat.color_char.is_empty() {
            let chars: Vec<char> = self.chat.color_char.chars().collect();
            if chars.len() != 1 || !chars[0].is_ascii() || chars[0].is_ascii_alphanumeric() {
                return Err(ConfigError::InvalidColorChar(self.chat.color_char.clone()));
            }
        }
        // Network timeouts: keepalive_timeout must be >= keepalive_interval
        let t = &self.network.timeouts;
        if t.keepalive_timeout_secs < t.keepalive_interval_secs {
            return Err(ConfigError::InvalidTimeout(format!(
                "keepalive_timeout_secs ({}) must be >= keepalive_interval_secs ({})",
                t.keepalive_timeout_secs, t.keepalive_interval_secs
            )));
        }
        if t.keepalive_interval_secs == 0 {
            return Err(ConfigError::InvalidTimeout(
                "keepalive_interval_secs must be > 0".to_string(),
            ));
        }
        // Weather timing: min must be <= max for each pair
        let w = &self.gameplay.weather;
        if w.rain_delay_min > w.rain_delay_max {
            return Err(ConfigError::InvalidWeatherTiming(format!(
                "rain_delay_min ({}) must be <= rain_delay_max ({})",
                w.rain_delay_min, w.rain_delay_max
            )));
        }
        if w.rain_duration_min > w.rain_duration_max {
            return Err(ConfigError::InvalidWeatherTiming(format!(
                "rain_duration_min ({}) must be <= rain_duration_max ({})",
                w.rain_duration_min, w.rain_duration_max
            )));
        }
        if w.thunder_delay_min > w.thunder_delay_max {
            return Err(ConfigError::InvalidWeatherTiming(format!(
                "thunder_delay_min ({}) must be <= thunder_delay_max ({})",
                w.thunder_delay_min, w.thunder_delay_max
            )));
        }
        if w.thunder_duration_min > w.thunder_duration_max {
            return Err(ConfigError::InvalidWeatherTiming(format!(
                "thunder_duration_min ({}) must be <= thunder_duration_max ({})",
                w.thunder_duration_min, w.thunder_duration_max
            )));
        }
        // World tuning: cache size and concurrent generations must be > 0
        if self.world.chunk_cache_size == 0 {
            return Err(ConfigError::InvalidWorldTuning(
                "chunk_cache_size must be > 0".to_string(),
            ));
        }
        if self.world.max_concurrent_chunk_generations == 0 {
            return Err(ConfigError::InvalidWorldTuning(
                "max_concurrent_chunk_generations must be > 0".to_string(),
            ));
        }
        Ok(())
    }

    /// Applies `OXIDIZED_{SECTION}_{FIELD}` environment variable overrides.
    ///
    /// Call **after** loading from file and **before** CLI flag overrides,
    /// giving the precedence: CLI > env vars > file > defaults (ADR-005/033).
    ///
    /// Invalid values are logged at `warn` level and silently skipped.
    pub fn apply_env_overrides(&mut self) {
        /// Reads `OXIDIZED_{SECTION}_{FIELD}`, parses to `$ty`, and assigns.
        macro_rules! env_override {
            ($self:expr, $section:ident . $field:ident, $ty:ty) => {
                let env_name = concat!(
                    "OXIDIZED_",
                    stringify!($section),
                    "_",
                    stringify!($field)
                )
                .to_ascii_uppercase();
                if let Ok(val) = std::env::var(&env_name) {
                    match val.parse::<$ty>() {
                        Ok(parsed) => {
                            $self.$section.$field = parsed;
                            info!(
                                env = %env_name,
                                value = %val,
                                "Config override from environment"
                            );
                        }
                        Err(_) => {
                            warn!(
                                env = %env_name,
                                value = %val,
                                expected = stringify!($ty),
                                "Ignoring invalid environment config override"
                            );
                        }
                    }
                }
            };
        }

        // [network]
        env_override!(self, network.port, u16);
        env_override!(self, network.ip, String);
        env_override!(self, network.is_online_mode, bool);
        env_override!(self, network.is_preventing_proxy_connections, bool);
        env_override!(self, network.compression_threshold, i32);
        env_override!(self, network.rate_limit, i32);
        env_override!(self, network.is_accepting_transfers, bool);

        // [gameplay]
        env_override!(self, gameplay.gamemode, String);
        env_override!(self, gameplay.difficulty, String);
        env_override!(self, gameplay.is_hardcore, bool);
        env_override!(self, gameplay.is_force_gamemode, bool);
        env_override!(self, gameplay.max_players, u32);
        env_override!(self, gameplay.spawn_protection, u32);
        env_override!(self, gameplay.max_world_size, i32);
        env_override!(self, gameplay.is_flight_allowed, bool);
        env_override!(self, gameplay.is_spawning_npcs, bool);
        env_override!(self, gameplay.is_spawning_animals, bool);
        env_override!(self, gameplay.is_spawning_monsters, bool);
        env_override!(self, gameplay.is_nether_allowed, bool);
        env_override!(self, gameplay.max_chained_neighbor_updates, i32);
        env_override!(self, gameplay.is_pvp_enabled, bool);

        // [world]
        env_override!(self, world.name, String);
        env_override!(self, world.seed, String);
        env_override!(self, world.is_generating_structures, bool);
        env_override!(self, world.view_distance, u32);
        env_override!(self, world.simulation_distance, u32);
        env_override!(self, world.region_file_compression, String);
        env_override!(self, world.chunk_cache_size, usize);
        env_override!(self, world.max_concurrent_chunk_generations, usize);

        // [display]
        env_override!(self, display.motd, String);
        env_override!(self, display.is_status_enabled, bool);
        env_override!(self, display.is_hiding_online_players, bool);
        env_override!(self, display.entity_broadcast_range_percentage, i32);
        env_override!(self, display.status_heartbeat_interval, i32);

        // [chat]
        env_override!(self, chat.color_char, String);

        // [admin]
        env_override!(self, admin.is_whitelist_enabled, bool);
        env_override!(self, admin.is_whitelist_enforced, bool);
        env_override!(self, admin.op_permission_level, i32);
        env_override!(self, admin.function_permission_level, i32);
        env_override!(self, admin.is_secure_profile_enforced, bool);
        env_override!(self, admin.is_logging_ips, bool);
        env_override!(self, admin.max_tick_time, i64);
        env_override!(self, admin.player_idle_timeout, i32);
        env_override!(self, admin.is_broadcasting_console_to_ops, bool);
        env_override!(self, admin.is_broadcasting_rcon_to_ops, bool);
        env_override!(self, admin.pause_when_empty_seconds, i32);

        // [rcon]
        env_override!(self, rcon.is_enabled, bool);
        env_override!(self, rcon.port, u16);
        env_override!(self, rcon.password, String);

        // [query]
        env_override!(self, query.is_enabled, bool);
        env_override!(self, query.port, u16);

        // [resource_pack]
        env_override!(self, resource_pack.url, String);
        env_override!(self, resource_pack.sha1, String);
        env_override!(self, resource_pack.prompt, String);
        env_override!(self, resource_pack.is_required, bool);

        // [management]
        env_override!(self, management.is_enabled, bool);
        env_override!(self, management.host, String);
        env_override!(self, management.port, u16);
        env_override!(self, management.secret, String);
        env_override!(self, management.is_tls_enabled, bool);

        // [packs]
        env_override!(self, packs.initial_enabled, String);
        env_override!(self, packs.initial_disabled, String);

        // [advanced]
        env_override!(self, advanced.text_filtering_config, String);
        env_override!(self, advanced.text_filtering_version, i32);
        env_override!(self, advanced.is_code_of_conduct_enabled, bool);
        env_override!(self, advanced.bug_report_link, String);
        env_override!(self, advanced.inbound_channel_capacity, usize);
        env_override!(self, advanced.outbound_channel_capacity, usize);
    }
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::needless_pass_by_value,
    clippy::panic,
    unsafe_code
)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    #[test]
    fn test_default_config_serializes_to_valid_toml() {
        let config = ServerConfig::default();
        let toml_str =
            toml::to_string_pretty(&config).expect("default config should serialize to TOML");
        let deserialized: ServerConfig =
            toml::from_str(&toml_str).expect("serialized TOML should deserialize back");
        assert_eq!(config, deserialized);
    }

    #[test]
    fn test_load_or_create_creates_default_file() {
        let dir = tempfile::tempdir().expect("should create tempdir");
        let path = dir.path().join("oxidized.toml");

        assert!(!path.exists());

        let config = ServerConfig::load_or_create(&path).expect("should create default");
        assert!(path.exists());
        assert_eq!(config, ServerConfig::default());

        // Verify the file contains TOML content.
        let contents = fs::read_to_string(&path).expect("should read");
        assert!(contents.contains("[network]"));
        assert!(contents.contains("[gameplay]"));
    }

    #[test]
    fn test_validate_accepts_valid_defaults() {
        let config = ServerConfig::default();
        assert!(config.validate().is_ok());
    }

    #[test]
    fn test_validate_rejects_invalid_port() {
        let mut config = ServerConfig::default();
        config.network.port = 0;
        let err = config.validate().unwrap_err();
        assert!(matches!(err, ConfigError::InvalidPort(0)));
    }

    #[test]
    fn test_validate_rejects_invalid_view_distance() {
        let mut config = ServerConfig::default();

        config.world.view_distance = 1;
        let err = config.validate().unwrap_err();
        assert!(matches!(err, ConfigError::InvalidViewDistance(1)));

        config.world.view_distance = 33;
        let err = config.validate().unwrap_err();
        assert!(matches!(err, ConfigError::InvalidViewDistance(33)));
    }

    #[test]
    fn test_validate_rejects_invalid_simulation_distance() {
        let mut config = ServerConfig::default();

        config.world.simulation_distance = 1;
        let err = config.validate().unwrap_err();
        assert!(matches!(err, ConfigError::InvalidSimulationDistance(1)));

        config.world.simulation_distance = 33;
        let err = config.validate().unwrap_err();
        assert!(matches!(err, ConfigError::InvalidSimulationDistance(33)));
    }

    #[test]
    fn test_validate_rejects_invalid_max_players() {
        let mut config = ServerConfig::default();
        config.gameplay.max_players = 0;
        let err = config.validate().unwrap_err();
        assert!(matches!(err, ConfigError::InvalidMaxPlayers(0)));
    }

    #[test]
    fn test_roundtrip_preserves_all_fields() {
        let dir = tempfile::tempdir().expect("should create tempdir");
        let path = dir.path().join("oxidized.toml");

        let config = ServerConfig {
            network: NetworkConfig {
                port: 19132,
                ip: "192.168.1.1".to_string(),
                is_online_mode: false,
                is_preventing_proxy_connections: true,
                compression_threshold: 512,
                rate_limit: 10,
                is_accepting_transfers: true,
                timeouts: NetworkTimeoutsConfig {
                    keepalive_interval_secs: 20,
                    keepalive_timeout_secs: 45,
                    login_timeout_secs: 60,
                    configuration_timeout_secs: 60,
                    write_timeout_secs: 45,
                },
                connection_rate_limit: RateLimitConfig {
                    max_connections_per_window: 20,
                    window_secs: 30,
                    cleanup_interval_secs: 120,
                },
            },
            gameplay: GameplayConfig {
                gamemode: "creative".to_string(),
                difficulty: "hard".to_string(),
                is_hardcore: true,
                is_force_gamemode: true,
                max_players: 100,
                spawn_protection: 32,
                max_world_size: 10000,
                is_flight_allowed: true,
                is_spawning_npcs: false,
                is_spawning_animals: false,
                is_spawning_monsters: false,
                is_nether_allowed: false,
                max_chained_neighbor_updates: 500_000,
                is_pvp_enabled: false,
                entity_tracking: EntityTrackingConfig {
                    player: 256,
                    animal: 80,
                    monster: 64,
                    misc: 48,
                    projectile: 32,
                    default: 40,
                },
                weather: WeatherConfig {
                    rain_delay_min: 6_000,
                    rain_delay_max: 90_000,
                    rain_duration_min: 6_000,
                    rain_duration_max: 12_000,
                    thunder_delay_min: 6_000,
                    thunder_delay_max: 90_000,
                    thunder_duration_min: 1_800,
                    thunder_duration_max: 7_800,
                },
            },
            world: WorldConfig {
                name: "custom_world".to_string(),
                seed: "12345".to_string(),
                is_generating_structures: false,
                view_distance: 16,
                simulation_distance: 8,
                region_file_compression: "none".to_string(),
                chunk_cache_size: 2048,
                max_concurrent_chunk_generations: 32,
            },
            display: DisplayConfig {
                motd: "Full Roundtrip Test".to_string(),
                is_status_enabled: false,
                is_hiding_online_players: true,
                entity_broadcast_range_percentage: 200,
                status_heartbeat_interval: 15,
            },
            chat: ChatConfig {
                color_char: "&".to_string(),
            },
            admin: AdminConfig {
                is_whitelist_enabled: true,
                is_whitelist_enforced: true,
                op_permission_level: 3,
                function_permission_level: 3,
                is_secure_profile_enforced: false,
                is_logging_ips: false,
                max_tick_time: 120_000,
                player_idle_timeout: 30,
                is_broadcasting_console_to_ops: false,
                is_broadcasting_rcon_to_ops: false,
                pause_when_empty_seconds: 120,
            },
            rcon: RconConfig {
                is_enabled: true,
                port: 25576,
                password: "secret123".to_string(),
            },
            query: QueryConfig {
                is_enabled: true,
                port: 25566,
            },
            resource_pack: ResourcePackConfig {
                url: "https://example.com/pack.zip".to_string(),
                sha1: "abc123def456".to_string(),
                prompt: "Please install".to_string(),
                is_required: true,
            },
            management: ManagementConfig {
                is_enabled: true,
                host: "mgmt.example.com".to_string(),
                port: 8443,
                secret: "mgmt-secret".to_string(),
                is_tls_enabled: true,
            },
            packs: PacksConfig {
                initial_enabled: "vanilla,fabric".to_string(),
                initial_disabled: "experimental".to_string(),
            },
            advanced: AdvancedConfig {
                text_filtering_config: "filter.json".to_string(),
                text_filtering_version: 2,
                is_code_of_conduct_enabled: true,
                bug_report_link: "https://bugs.example.com".to_string(),
                inbound_channel_capacity: 64,
                outbound_channel_capacity: 256,
            },
            extra: BTreeMap::new(),
        };

        config.save(&path).expect("save should succeed");
        let loaded = ServerConfig::load_or_create(&path).expect("load should succeed");
        assert_eq!(config, loaded);
    }

    // -----------------------------------------------------------------------
    // Property-based tests (proptest)
    // -----------------------------------------------------------------------

    proptest! {
        #[test]
        fn test_roundtrip_invariant_for_network_config(
            port in 1u16..=65535u16,
            is_online_mode in proptest::bool::ANY,
            compression in -1i32..1024i32,
            rate_limit in 0i32..1000i32,
        ) {
            let mut config = ServerConfig::default();
            config.network.port = port;
            config.network.is_online_mode = is_online_mode;
            config.network.compression_threshold = compression;
            config.network.rate_limit = rate_limit;

            let toml_str = toml::to_string_pretty(&config).unwrap();
            let loaded: ServerConfig = toml::from_str(&toml_str).unwrap();

            assert_eq!(config.network.port, loaded.network.port);
            assert_eq!(config.network.is_online_mode, loaded.network.is_online_mode);
            assert_eq!(
                config.network.compression_threshold,
                loaded.network.compression_threshold
            );
            assert_eq!(config.network.rate_limit, loaded.network.rate_limit);
        }
    }

    proptest! {
        #[test]
        fn test_roundtrip_invariant_for_gameplay_config(
            max_players in 1u32..1000u32,
            view_distance in 2u32..=32u32,
            simulation_distance in 2u32..=32u32,
            is_hardcore in proptest::bool::ANY,
            spawn_protection in 0u32..100u32,
        ) {
            let mut config = ServerConfig::default();
            config.gameplay.max_players = max_players;
            config.world.view_distance = view_distance;
            config.world.simulation_distance = simulation_distance;
            config.gameplay.is_hardcore = is_hardcore;
            config.gameplay.spawn_protection = spawn_protection;

            let toml_str = toml::to_string_pretty(&config).unwrap();
            let loaded: ServerConfig = toml::from_str(&toml_str).unwrap();

            assert_eq!(config.gameplay.max_players, loaded.gameplay.max_players);
            assert_eq!(config.world.view_distance, loaded.world.view_distance);
            assert_eq!(
                config.world.simulation_distance,
                loaded.world.simulation_distance
            );
            assert_eq!(config.gameplay.is_hardcore, loaded.gameplay.is_hardcore);
            assert_eq!(
                config.gameplay.spawn_protection,
                loaded.gameplay.spawn_protection
            );
        }
    }

    proptest! {
        #[test]
        fn test_roundtrip_invariant_for_string_fields(
            motd in "[a-zA-Z0-9 ]{0,50}",
            world_name in "[a-zA-Z0-9_]{1,30}",
            seed in "[a-zA-Z0-9]{0,20}",
        ) {
            let mut config = ServerConfig::default();
            config.display.motd = motd.clone();
            config.world.name = world_name.clone();
            config.world.seed = seed.clone();

            let toml_str = toml::to_string_pretty(&config).unwrap();
            let loaded: ServerConfig = toml::from_str(&toml_str).unwrap();

            assert_eq!(motd, loaded.display.motd);
            assert_eq!(world_name, loaded.world.name);
            assert_eq!(seed, loaded.world.seed);
        }
    }

    // -----------------------------------------------------------------------
    // Snapshot test (insta)
    // -----------------------------------------------------------------------

    #[test]
    fn test_default_config_snapshot() {
        let config = ServerConfig::default();
        let toml_str = toml::to_string_pretty(&config).unwrap();
        insta::assert_snapshot!(toml_str);
    }

    // -----------------------------------------------------------------------
    // Boundary validation tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_validate_port_accepts_boundary_values() {
        let mut config = ServerConfig::default();
        config.network.port = 1;
        assert!(config.validate().is_ok(), "port 1 should be valid");

        config.network.port = 65535;
        assert!(config.validate().is_ok(), "port 65535 should be valid");
    }

    #[test]
    fn test_validate_view_distance_accepts_boundary_values() {
        let mut config = ServerConfig::default();
        config.world.view_distance = 2;
        assert!(config.validate().is_ok(), "view_distance 2 should be valid");

        config.world.view_distance = 32;
        assert!(
            config.validate().is_ok(),
            "view_distance 32 should be valid"
        );
    }

    #[test]
    fn test_validate_simulation_distance_accepts_boundary_values() {
        let mut config = ServerConfig::default();
        config.world.simulation_distance = 2;
        assert!(config.validate().is_ok(), "sim_distance 2 should be valid");

        config.world.simulation_distance = 32;
        assert!(config.validate().is_ok(), "sim_distance 32 should be valid");
    }

    #[test]
    fn test_validate_rejects_rcon_port_zero_when_enabled() {
        let mut config = ServerConfig::default();
        config.rcon.is_enabled = true;
        config.rcon.port = 0;
        assert!(
            matches!(config.validate(), Err(ConfigError::InvalidPort(0))),
            "rcon port 0 with enabled=true should fail"
        );
    }

    #[test]
    fn test_validate_allows_rcon_port_zero_when_disabled() {
        let mut config = ServerConfig::default();
        config.rcon.is_enabled = false;
        config.rcon.port = 0;
        assert!(
            config.validate().is_ok(),
            "rcon port 0 with enabled=false should be ok"
        );
    }

    #[test]
    fn test_validate_rejects_query_port_zero_when_enabled() {
        let mut config = ServerConfig::default();
        config.query.is_enabled = true;
        config.query.port = 0;
        assert!(
            matches!(config.validate(), Err(ConfigError::InvalidPort(0))),
            "query port 0 with enabled=true should fail"
        );
    }

    #[test]
    fn test_validate_allows_query_port_zero_when_disabled() {
        let mut config = ServerConfig::default();
        config.query.is_enabled = false;
        config.query.port = 0;
        assert!(
            config.validate().is_ok(),
            "query port 0 with enabled=false should be ok"
        );
    }

    // -----------------------------------------------------------------------
    // Partial TOML tests (missing sections get defaults)
    // -----------------------------------------------------------------------

    #[test]
    fn test_partial_toml_gets_defaults_for_missing_sections() {
        let partial = r#"
[network]
port = 19132
"#;
        let config: ServerConfig = toml::from_str(partial).unwrap();
        assert_eq!(config.network.port, 19132);
        // All other sections should be defaults
        assert_eq!(config.gameplay.max_players, 20);
        assert_eq!(config.world.name, "world");
        assert_eq!(config.display.motd, "An Oxidized Minecraft Server");
        assert!(!config.rcon.is_enabled);
    }

    #[test]
    fn test_empty_toml_produces_all_defaults() {
        let config: ServerConfig = toml::from_str("").unwrap();
        let default = ServerConfig::default();
        assert_eq!(config, default);
    }

    #[test]
    fn test_unknown_keys_are_preserved_through_roundtrip() {
        let input = r#"
[network]
port = 25565

[unknown_section]
key = "value"
"#;
        let config: ServerConfig = toml::from_str(input).unwrap();
        assert_eq!(config.network.port, 25565);
        // Unknown top-level section is captured in the `extra` map
        assert!(
            config.extra.contains_key("unknown_section"),
            "unknown sections should be preserved in extra"
        );

        // Roundtrip: serialize back and re-parse
        let serialized = toml::to_string_pretty(&config).unwrap();
        let reloaded: ServerConfig = toml::from_str(&serialized).unwrap();
        assert!(
            reloaded.extra.contains_key("unknown_section"),
            "unknown sections should survive roundtrip"
        );
    }

    // -----------------------------------------------------------------------
    // TOML format edge cases
    // -----------------------------------------------------------------------

    #[test]
    fn test_toml_with_inline_comments_parses_correctly() {
        let input = r#"
# Server configuration
[network]
port = 25565 # Standard MC port
is_online_mode = true
"#;
        let config: ServerConfig = toml::from_str(input).unwrap();
        assert_eq!(config.network.port, 25565);
        assert!(config.network.is_online_mode);
    }

    #[test]
    fn test_toml_with_extra_whitespace_parses_correctly() {
        let input = r#"
[network]
port   =   19132
is_online_mode   =   false
"#;
        let config: ServerConfig = toml::from_str(input).unwrap();
        assert_eq!(config.network.port, 19132);
        assert!(!config.network.is_online_mode);
    }

    // -----------------------------------------------------------------------
    // File I/O integration tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_save_and_reload_produces_identical_config() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("oxidized.toml");

        let mut config = ServerConfig::default();
        config.network.port = 19132;
        config.gameplay.max_players = 100;
        config.display.motd = "Test Server".to_string();
        config.rcon.is_enabled = true;
        config.rcon.password = "secret".to_string();

        config.save(&path).unwrap();
        let loaded = ServerConfig::load_or_create(&path).unwrap();

        assert_eq!(config, loaded);
    }

    #[test]
    fn test_saved_file_starts_with_header_comment() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("oxidized.toml");

        let config = ServerConfig::default();
        config.save(&path).unwrap();

        let content = fs::read_to_string(&path).unwrap();
        assert!(
            content.starts_with("# Oxidized"),
            "file should start with header comment"
        );
    }

    // -----------------------------------------------------------------------
    // Security — secret redaction in Debug output
    // -----------------------------------------------------------------------

    #[test]
    fn test_debug_redacts_rcon_password() {
        let rcon = RconConfig {
            password: "super_secret_password".to_string(),
            ..RconConfig::default()
        };
        let debug_output = format!("{:?}", rcon);
        assert!(
            !debug_output.contains("super_secret_password"),
            "Debug output must not contain the actual password"
        );
        assert!(
            debug_output.contains("[REDACTED]"),
            "Debug output should show [REDACTED]"
        );
    }

    #[test]
    fn test_debug_redacts_management_secret() {
        let mgmt = ManagementConfig {
            secret: "top_secret_key".to_string(),
            ..ManagementConfig::default()
        };
        let debug_output = format!("{:?}", mgmt);
        assert!(
            !debug_output.contains("top_secret_key"),
            "Debug output must not contain the actual secret"
        );
        assert!(
            debug_output.contains("[REDACTED]"),
            "Debug output should show [REDACTED]"
        );
    }

    // ── ChatConfig / color_char validation ───────────────────────────

    #[test]
    fn test_color_char_default_is_ampersand() {
        let chat = ChatConfig::default();
        assert_eq!(chat.color_char, "&");
        assert_eq!(chat.color_char(), Some('&'));
    }

    #[test]
    fn test_color_char_empty_means_disabled() {
        let chat = ChatConfig {
            color_char: String::new(),
        };
        assert_eq!(chat.color_char(), None);
    }

    #[test]
    fn test_color_char_valid_symbols() {
        for ch in ['&', '#', '!', '@', '$', '%', '^', '~'] {
            let mut cfg = ServerConfig::default();
            cfg.chat.color_char = ch.to_string();
            cfg.validate()
                .unwrap_or_else(|e| panic!("'{ch}' should be valid: {e}"));
        }
    }

    #[test]
    fn test_color_char_rejects_alphanumeric() {
        for ch in ['a', 'Z', '0', '9'] {
            let mut cfg = ServerConfig::default();
            cfg.chat.color_char = ch.to_string();
            assert!(cfg.validate().is_err(), "'{ch}' should be rejected");
        }
    }

    #[test]
    fn test_color_char_rejects_multi_char() {
        let mut cfg = ServerConfig::default();
        cfg.chat.color_char = "&&".to_string();
        assert!(cfg.validate().is_err(), "multi-char should be rejected");
    }

    #[test]
    fn test_color_char_rejects_non_ascii() {
        let mut cfg = ServerConfig::default();
        cfg.chat.color_char = "§".to_string();
        assert!(cfg.validate().is_err(), "non-ASCII should be rejected");
    }

    #[test]
    fn test_color_char_empty_passes_validation() {
        let mut cfg = ServerConfig::default();
        cfg.chat.color_char = String::new();
        cfg.validate().unwrap();
    }

    // -----------------------------------------------------------------------
    // Environment variable override tests
    // -----------------------------------------------------------------------

    /// Helper to clean up env vars set during a test.
    fn remove_env_vars(vars: &[&str]) {
        for var in vars {
            unsafe { std::env::remove_var(var) };
        }
    }

    #[test]
    #[serial_test::serial]
    fn test_env_override_u16_port() {
        let vars = ["OXIDIZED_NETWORK_PORT"];
        unsafe { std::env::set_var("OXIDIZED_NETWORK_PORT", "25566") };

        let mut config = ServerConfig::default();
        assert_eq!(config.network.port, 25565);
        config.apply_env_overrides();
        assert_eq!(config.network.port, 25566);

        remove_env_vars(&vars);
    }

    #[test]
    #[serial_test::serial]
    fn test_env_override_bool_true() {
        let vars = ["OXIDIZED_GAMEPLAY_IS_HARDCORE"];
        unsafe { std::env::set_var("OXIDIZED_GAMEPLAY_IS_HARDCORE", "true") };

        let mut config = ServerConfig::default();
        assert!(!config.gameplay.is_hardcore);
        config.apply_env_overrides();
        assert!(config.gameplay.is_hardcore);

        remove_env_vars(&vars);
    }

    #[test]
    #[serial_test::serial]
    fn test_env_override_bool_false() {
        let vars = ["OXIDIZED_NETWORK_IS_ONLINE_MODE"];
        unsafe { std::env::set_var("OXIDIZED_NETWORK_IS_ONLINE_MODE", "false") };

        let mut config = ServerConfig::default();
        assert!(config.network.is_online_mode);
        config.apply_env_overrides();
        assert!(!config.network.is_online_mode);

        remove_env_vars(&vars);
    }

    #[test]
    #[serial_test::serial]
    fn test_env_override_u32() {
        let vars = ["OXIDIZED_GAMEPLAY_MAX_PLAYERS"];
        unsafe { std::env::set_var("OXIDIZED_GAMEPLAY_MAX_PLAYERS", "100") };

        let mut config = ServerConfig::default();
        assert_eq!(config.gameplay.max_players, 20);
        config.apply_env_overrides();
        assert_eq!(config.gameplay.max_players, 100);

        remove_env_vars(&vars);
    }

    #[test]
    #[serial_test::serial]
    fn test_env_override_i32() {
        let vars = ["OXIDIZED_NETWORK_COMPRESSION_THRESHOLD"];
        unsafe { std::env::set_var("OXIDIZED_NETWORK_COMPRESSION_THRESHOLD", "-1") };

        let mut config = ServerConfig::default();
        assert_eq!(config.network.compression_threshold, 256);
        config.apply_env_overrides();
        assert_eq!(config.network.compression_threshold, -1);

        remove_env_vars(&vars);
    }

    #[test]
    #[serial_test::serial]
    fn test_env_override_i64() {
        let vars = ["OXIDIZED_ADMIN_MAX_TICK_TIME"];
        unsafe { std::env::set_var("OXIDIZED_ADMIN_MAX_TICK_TIME", "120000") };

        let mut config = ServerConfig::default();
        assert_eq!(config.admin.max_tick_time, 60_000);
        config.apply_env_overrides();
        assert_eq!(config.admin.max_tick_time, 120_000);

        remove_env_vars(&vars);
    }

    #[test]
    #[serial_test::serial]
    fn test_env_override_string() {
        let vars = ["OXIDIZED_DISPLAY_MOTD"];
        unsafe { std::env::set_var("OXIDIZED_DISPLAY_MOTD", "Hello Docker!") };

        let mut config = ServerConfig::default();
        config.apply_env_overrides();
        assert_eq!(config.display.motd, "Hello Docker!");

        remove_env_vars(&vars);
    }

    #[test]
    #[serial_test::serial]
    fn test_env_override_invalid_value_is_ignored() {
        let vars = ["OXIDIZED_NETWORK_PORT"];
        unsafe { std::env::set_var("OXIDIZED_NETWORK_PORT", "not_a_number") };

        let mut config = ServerConfig::default();
        config.apply_env_overrides();
        assert_eq!(
            config.network.port, 25565,
            "invalid value should be ignored"
        );

        remove_env_vars(&vars);
    }

    #[test]
    #[serial_test::serial]
    fn test_env_override_invalid_bool_is_ignored() {
        let vars = ["OXIDIZED_GAMEPLAY_IS_HARDCORE"];
        unsafe { std::env::set_var("OXIDIZED_GAMEPLAY_IS_HARDCORE", "yes") };

        let mut config = ServerConfig::default();
        config.apply_env_overrides();
        assert!(
            !config.gameplay.is_hardcore,
            "invalid bool should be ignored"
        );

        remove_env_vars(&vars);
    }

    #[test]
    #[serial_test::serial]
    fn test_env_override_multiple_fields() {
        let vars = [
            "OXIDIZED_NETWORK_PORT",
            "OXIDIZED_GAMEPLAY_MAX_PLAYERS",
            "OXIDIZED_WORLD_VIEW_DISTANCE",
            "OXIDIZED_DISPLAY_MOTD",
        ];
        unsafe {
            std::env::set_var("OXIDIZED_NETWORK_PORT", "19132");
            std::env::set_var("OXIDIZED_GAMEPLAY_MAX_PLAYERS", "50");
            std::env::set_var("OXIDIZED_WORLD_VIEW_DISTANCE", "16");
            std::env::set_var("OXIDIZED_DISPLAY_MOTD", "Container Server");
        }

        let mut config = ServerConfig::default();
        config.apply_env_overrides();

        assert_eq!(config.network.port, 19132);
        assert_eq!(config.gameplay.max_players, 50);
        assert_eq!(config.world.view_distance, 16);
        assert_eq!(config.display.motd, "Container Server");

        remove_env_vars(&vars);
    }

    #[test]
    #[serial_test::serial]
    fn test_env_override_does_not_affect_unset_fields() {
        let vars = ["OXIDIZED_NETWORK_PORT"];
        unsafe { std::env::set_var("OXIDIZED_NETWORK_PORT", "19132") };

        let mut config = ServerConfig::default();
        let default = ServerConfig::default();
        config.apply_env_overrides();

        assert_eq!(config.network.port, 19132);
        // All other fields unchanged
        assert_eq!(
            config.network.is_online_mode,
            default.network.is_online_mode
        );
        assert_eq!(config.gameplay, default.gameplay);
        assert_eq!(config.world, default.world);

        remove_env_vars(&vars);
    }

    #[test]
    #[serial_test::serial]
    fn test_env_override_rcon_password() {
        let vars = ["OXIDIZED_RCON_PASSWORD"];
        unsafe { std::env::set_var("OXIDIZED_RCON_PASSWORD", "s3cret") };

        let mut config = ServerConfig::default();
        config.apply_env_overrides();
        assert_eq!(config.rcon.password, "s3cret");

        remove_env_vars(&vars);
    }

    #[test]
    #[serial_test::serial]
    fn test_env_override_query_port() {
        let vars = ["OXIDIZED_QUERY_PORT"];
        unsafe { std::env::set_var("OXIDIZED_QUERY_PORT", "25567") };

        let mut config = ServerConfig::default();
        config.apply_env_overrides();
        assert_eq!(config.query.port, 25567);

        remove_env_vars(&vars);
    }

    #[test]
    #[serial_test::serial]
    fn test_env_override_advanced_fields() {
        let vars = [
            "OXIDIZED_ADVANCED_INBOUND_CHANNEL_CAPACITY",
            "OXIDIZED_ADVANCED_TEXT_FILTERING_VERSION",
        ];
        unsafe {
            std::env::set_var("OXIDIZED_ADVANCED_INBOUND_CHANNEL_CAPACITY", "64");
            std::env::set_var("OXIDIZED_ADVANCED_TEXT_FILTERING_VERSION", "3");
        }

        let mut config = ServerConfig::default();
        config.apply_env_overrides();
        assert_eq!(config.advanced.inbound_channel_capacity, 64);
        assert_eq!(config.advanced.text_filtering_version, 3);

        remove_env_vars(&vars);
    }
}
