//! Synchronized registry data for the Minecraft Configuration protocol state.
//!
//! Bundles all 28 registries from `registries.json` (generated by
//! `tools/bundle_registries.py`) and provides conversion from JSON to NBT
//! so entries can be sent in `ClientboundRegistryDataPacket`.

use std::collections::HashMap;
use std::sync::LazyLock;

use indexmap::IndexMap;
use oxidized_nbt::{NbtCompound, NbtList, NbtTag};

use crate::packets::configuration::clientbound_update_tags::{
    ClientboundUpdateTagsPacket, TagEntry, TagRegistry,
};
use crate::types::resource_location::ResourceLocation;

/// Raw registry JSON bundled at compile time.
const REGISTRIES_JSON: &str = include_str!("data/registries.json");

/// Raw tag JSON bundled at compile time (generated by `tools/bundle_tags.py`).
const TAGS_JSON: &str = include_str!("data/tags.json");

/// Registry name → entries (entry name → JSON value).
///
/// The inner map is an [`IndexMap`] to preserve the JSON insertion order,
/// which matches vanilla's registration order. This is critical because
/// registry packets assign client-side IDs (0, 1, 2, …) based on the
/// order entries are received. Using `HashMap` here would randomize the
/// order on each process start, causing dimension_type mismatches.
type RegistryMap = HashMap<String, IndexMap<String, serde_json::Value>>;

/// Tag registry name → tag name → entry IDs.
type TagMap = HashMap<String, HashMap<String, Vec<i32>>>;

/// All synchronized registry data, parsed once on first access.
///
/// # Panics
///
/// Panics if the bundled `registries.json` is malformed. This is a compile-time
/// artifact so the panic is not reachable in practice.
static REGISTRIES: LazyLock<RegistryMap> = LazyLock::new(|| {
    // SAFETY rationale for expect: registries.json is generated by our own tooling
    // and included at compile time — a parse failure here is a build-time bug.
    #[allow(clippy::expect_used)]
    serde_json::from_str(REGISTRIES_JSON).expect("bundled registries.json is valid")
});

/// All tag data, parsed once on first access.
///
/// # Panics
///
/// Panics if the bundled `tags.json` is malformed.
static TAGS: LazyLock<TagMap> = LazyLock::new(|| {
    #[allow(clippy::expect_used)]
    serde_json::from_str(TAGS_JSON).expect("bundled tags.json is valid")
});

/// The ordered list of synchronized registries (same order as vanilla's
/// `RegistryDataLoader`).
pub const SYNCHRONIZED_REGISTRIES: &[&str] = &[
    "minecraft:worldgen/biome",
    "minecraft:chat_type",
    "minecraft:trim_pattern",
    "minecraft:trim_material",
    "minecraft:wolf_variant",
    "minecraft:wolf_sound_variant",
    "minecraft:pig_variant",
    "minecraft:pig_sound_variant",
    "minecraft:frog_variant",
    "minecraft:cat_variant",
    "minecraft:cat_sound_variant",
    "minecraft:cow_sound_variant",
    "minecraft:cow_variant",
    "minecraft:chicken_sound_variant",
    "minecraft:chicken_variant",
    "minecraft:zombie_nautilus_variant",
    "minecraft:painting_variant",
    "minecraft:dimension_type",
    "minecraft:damage_type",
    "minecraft:banner_pattern",
    "minecraft:enchantment",
    "minecraft:jukebox_song",
    "minecraft:instrument",
    "minecraft:test_environment",
    "minecraft:test_instance",
    "minecraft:dialog",
    "minecraft:world_clock",
    "minecraft:timeline",
];

/// Errors that can occur when working with registry data.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum RegistryError {
    /// The requested registry name is not in the bundled data.
    #[error("unknown registry: {0}")]
    UnknownRegistry(String),

    /// A JSON value could not be converted to NBT.
    #[error("failed to convert JSON to NBT: {0}")]
    ConversionError(String),
}

/// Returns all entries for a given registry as `(resource_location, NbtCompound)` pairs.
///
/// The JSON values are converted to NBT compounds using [`json_to_nbt_compound`].
///
/// # Errors
///
/// Returns [`RegistryError::UnknownRegistry`] if the registry is not in the
/// bundled data, or [`RegistryError::ConversionError`] if a JSON value cannot
/// be converted to NBT.
pub fn get_registry_entries(
    registry_name: &str,
) -> Result<Vec<(String, NbtCompound)>, RegistryError> {
    let registries = &*REGISTRIES;
    let entries = registries
        .get(registry_name)
        .ok_or_else(|| RegistryError::UnknownRegistry(registry_name.to_string()))?;

    let mut result = Vec::with_capacity(entries.len());
    for (name, value) in entries {
        let compound = json_to_nbt_compound(value)?;
        result.push((name.clone(), compound));
    }
    Ok(result)
}

/// Returns the index of an entry within a registry, matching the order
/// entries are sent to the client in `ClientboundRegistryDataPacket`.
///
/// The client assigns IDs (0, 1, 2, …) based on the order entries are
/// received, so this index is the client-side ID for the entry.
///
/// # Errors
///
/// Returns [`RegistryError::UnknownRegistry`] if the registry or entry name
/// is not found.
pub fn get_registry_entry_index(
    registry_name: &str,
    entry_name: &str,
) -> Result<i32, RegistryError> {
    let registries = &*REGISTRIES;
    let entries = registries
        .get(registry_name)
        .ok_or_else(|| RegistryError::UnknownRegistry(registry_name.to_string()))?;

    entries
        .get_index_of(entry_name)
        .map(|idx| idx as i32)
        .ok_or_else(|| {
            RegistryError::UnknownRegistry(format!("{registry_name}/{entry_name}"))
        })
}

/// Builds a [`ClientboundUpdateTagsPacket`] from the bundled tag data.
///
/// Reads `tags.json` (generated by `tools/bundle_tags.py`) and constructs
/// the packet with all tag registries that have non-empty tags.
///
/// # Panics
///
/// Panics if bundled tag data contains invalid `ResourceLocation` strings.
/// This is a compile-time artifact so the panic is not reachable in practice.
pub fn build_tags_packet() -> ClientboundUpdateTagsPacket {
    let tags = &*TAGS;

    let mut registries = Vec::with_capacity(tags.len());

    for (registry_name, tag_map) in tags {
        // Only skip registries with zero tags (vanilla's NetworkPayload.isEmpty()).
        // Tags with empty entry lists are still sent — the client needs them for
        // registry freezing (e.g. minecraft:dialog has tags with no entries).
        if tag_map.is_empty() {
            continue;
        }

        #[allow(clippy::expect_used)]
        let registry = ResourceLocation::from_string(registry_name)
            .expect("bundled tag registry name is a valid ResourceLocation");

        let mut tag_entries = Vec::with_capacity(tag_map.len());
        for (tag_name, entry_ids) in tag_map {
            #[allow(clippy::expect_used)]
            let name = ResourceLocation::from_string(tag_name)
                .expect("bundled tag name is a valid ResourceLocation");

            tag_entries.push(TagEntry {
                name,
                entries: entry_ids.clone(),
            });
        }

        registries.push(TagRegistry {
            registry,
            tags: tag_entries,
        });
    }

    ClientboundUpdateTagsPacket { tags: registries }
}

// ── JSON → NBT conversion ──────────────────────────────────────────────────

/// Converts a JSON object to an [`NbtCompound`].
///
/// # Errors
///
/// Returns [`RegistryError::ConversionError`] if the top-level value is not a
/// JSON object, or if any nested value cannot be converted.
pub fn json_to_nbt_compound(value: &serde_json::Value) -> Result<NbtCompound, RegistryError> {
    match value {
        serde_json::Value::Object(map) => {
            let mut compound = NbtCompound::new();
            for (key, val) in map {
                if val.is_null() {
                    continue;
                }
                let tag = json_to_nbt_tag(val)?;
                compound.put(key.as_str(), tag);
            }
            Ok(compound)
        },
        other => Err(RegistryError::ConversionError(format!(
            "expected JSON object, got {other}"
        ))),
    }
}

/// Converts an arbitrary JSON value to an [`NbtTag`].
///
/// Mapping rules:
/// - `bool` → `Byte` (1 or 0)
/// - integer (no fractional part, fits `i32`) → `Int`
/// - integer (no fractional part, fits `i64`) → `Long`
/// - number with fractional part → `Float`
/// - string → `String`
/// - array → `List` (element type inferred from first element; empty → empty byte list)
/// - object → `Compound`
/// - null → should be skipped by the caller (not reached here)
fn json_to_nbt_tag(value: &serde_json::Value) -> Result<NbtTag, RegistryError> {
    match value {
        serde_json::Value::Bool(b) => Ok(NbtTag::Byte(i8::from(*b))),

        serde_json::Value::Number(n) => {
            if let Some(i) = n.as_i64() {
                if i >= i64::from(i32::MIN) && i <= i64::from(i32::MAX) {
                    Ok(NbtTag::Int(i as i32))
                } else {
                    Ok(NbtTag::Long(i))
                }
            } else if let Some(f) = n.as_f64() {
                Ok(NbtTag::Float(f as f32))
            } else {
                Err(RegistryError::ConversionError(format!(
                    "unsupported number: {n}"
                )))
            }
        },

        serde_json::Value::String(s) => Ok(NbtTag::String(s.clone())),

        serde_json::Value::Array(arr) => {
            if arr.is_empty() {
                return Ok(NbtTag::List(NbtList::empty()));
            }
            let first_tag = json_to_nbt_tag(&arr[0])?;
            let mut list = NbtList::new(first_tag.type_id());
            list.push(first_tag)
                .map_err(|e| RegistryError::ConversionError(format!("list push error: {e}")))?;
            for item in &arr[1..] {
                let tag = json_to_nbt_tag(item)?;
                list.push(tag)
                    .map_err(|e| RegistryError::ConversionError(format!("list push error: {e}")))?;
            }
            Ok(NbtTag::List(list))
        },

        serde_json::Value::Object(_) => {
            let compound = json_to_nbt_compound(value)?;
            Ok(NbtTag::Compound(compound))
        },

        serde_json::Value::Null => Err(RegistryError::ConversionError(
            "unexpected null value".to_string(),
        )),
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

    use super::*;
    use crate::codec::Packet;

    #[test]
    fn test_all_registries_loadable() {
        for &name in SYNCHRONIZED_REGISTRIES {
            let entries = get_registry_entries(name)
                .unwrap_or_else(|e| panic!("failed to load registry {name}: {e}"));
            assert!(
                !entries.is_empty(),
                "registry {name} should have at least one entry"
            );
        }
    }

    #[test]
    fn test_dimension_type_overworld_has_expected_fields() {
        let entries = get_registry_entries("minecraft:dimension_type").unwrap();
        let (_, overworld) = entries
            .iter()
            .find(|(name, _)| name == "minecraft:overworld")
            .expect("overworld dimension type should exist");

        assert!(overworld.contains_key("height"));
        assert!(overworld.contains_key("min_y"));
        assert!(overworld.contains_key("has_skylight"));
        assert_eq!(overworld.get_int("height"), Some(384));
        assert_eq!(overworld.get_int("min_y"), Some(-64));
    }

    #[test]
    fn test_json_to_nbt_integers() {
        let json: serde_json::Value = serde_json::json!({"small": 42, "negative": -10});
        let compound = json_to_nbt_compound(&json).unwrap();

        assert_eq!(compound.get_int("small"), Some(42));
        assert_eq!(compound.get_int("negative"), Some(-10));
    }

    #[test]
    fn test_json_to_nbt_large_integer_becomes_long() {
        let big = i64::from(i32::MAX) + 1;
        let json: serde_json::Value = serde_json::json!({"big": big});
        let compound = json_to_nbt_compound(&json).unwrap();

        assert_eq!(compound.get_long("big"), Some(big));
    }

    #[test]
    fn test_json_to_nbt_floats() {
        let json: serde_json::Value = serde_json::json!({"temp": 0.8, "scale": 1.5});
        let compound = json_to_nbt_compound(&json).unwrap();

        assert_eq!(compound.get_float("temp"), Some(0.8_f32));
        assert_eq!(compound.get_float("scale"), Some(1.5_f32));
    }

    #[test]
    fn test_json_to_nbt_boolean() {
        let json: serde_json::Value = serde_json::json!({"flag": true, "off": false});
        let compound = json_to_nbt_compound(&json).unwrap();

        assert_eq!(compound.get_byte("flag"), Some(1));
        assert_eq!(compound.get_byte("off"), Some(0));
    }

    #[test]
    fn test_json_to_nbt_nested() {
        let json: serde_json::Value = serde_json::json!({
            "outer": {
                "inner_str": "hello",
                "inner_int": 99
            },
            "list": [1, 2, 3]
        });
        let compound = json_to_nbt_compound(&json).unwrap();

        let outer = compound.get_compound("outer").expect("outer compound");
        assert_eq!(outer.get_string("inner_str"), Some("hello"));
        assert_eq!(outer.get_int("inner_int"), Some(99));

        let list = compound.get_list("list").expect("list");
        assert_eq!(list.len(), 3);
        assert_eq!(list.get(0).and_then(NbtTag::as_int), Some(1));
        assert_eq!(list.get(2).and_then(NbtTag::as_int), Some(3));
    }

    #[test]
    fn test_json_to_nbt_null_fields_skipped() {
        let json: serde_json::Value = serde_json::json!({"present": 1, "absent": null});
        let compound = json_to_nbt_compound(&json).unwrap();

        assert_eq!(compound.get_int("present"), Some(1));
        assert!(!compound.contains_key("absent"));
    }

    #[test]
    fn test_json_to_nbt_empty_array() {
        let json: serde_json::Value = serde_json::json!({"empty": []});
        let compound = json_to_nbt_compound(&json).unwrap();

        let list = compound.get_list("empty").expect("empty list");
        assert!(list.is_empty());
    }

    #[test]
    fn test_json_to_nbt_string_array() {
        let json: serde_json::Value = serde_json::json!({"params": ["sender", "content"]});
        let compound = json_to_nbt_compound(&json).unwrap();

        let list = compound.get_list("params").expect("params list");
        assert_eq!(list.len(), 2);
        assert_eq!(list.get(0).and_then(NbtTag::as_str), Some("sender"));
        assert_eq!(list.get(1).and_then(NbtTag::as_str), Some("content"));
    }

    #[test]
    fn test_unknown_registry_returns_error() {
        let result = get_registry_entries("minecraft:nonexistent");
        assert!(result.is_err());
        assert!(matches!(
            result.unwrap_err(),
            RegistryError::UnknownRegistry(_)
        ));
    }

    #[test]
    fn test_chat_type_registry() {
        let entries = get_registry_entries("minecraft:chat_type").unwrap();
        let has_chat = entries.iter().any(|(name, _)| name == "minecraft:chat");
        assert!(has_chat, "chat_type registry should contain minecraft:chat");
    }

    #[test]
    fn test_build_tags_packet_has_registries() {
        let packet = build_tags_packet();
        // Should have multiple tag registries (block, item, fluid, enchantment, etc.)
        assert!(
            packet.tags.len() >= 10,
            "expected at least 10 tag registries, got {}",
            packet.tags.len()
        );

        // Verify block tags exist and have entries
        let block_reg = packet
            .tags
            .iter()
            .find(|r| r.registry.to_string() == "minecraft:block")
            .expect("block tag registry should exist");
        assert!(
            block_reg.tags.len() > 100,
            "expected many block tags, got {}",
            block_reg.tags.len()
        );

        // Verify enchantment tags exist
        let enchant_reg = packet
            .tags
            .iter()
            .find(|r| r.registry.to_string() == "minecraft:enchantment")
            .expect("enchantment tag registry should exist");
        assert!(
            !enchant_reg.tags.is_empty(),
            "enchantment tags should not be empty"
        );
    }

    #[test]
    fn test_build_tags_packet_roundtrip() {
        let packet = build_tags_packet();
        let encoded = packet.encode();
        let decoded =
            ClientboundUpdateTagsPacket::decode(encoded.freeze()).expect("decode should succeed");
        assert_eq!(decoded, packet);
    }

    #[test]
    fn test_dimension_type_overworld_is_index_zero() {
        let idx = get_registry_entry_index("minecraft:dimension_type", "minecraft:overworld")
            .expect("overworld should exist in dimension_type registry");
        assert_eq!(idx, 0, "overworld must be index 0 in dimension_type registry");
    }

    #[test]
    fn test_registry_entry_index_preserves_order() {
        let entries = get_registry_entries("minecraft:dimension_type").unwrap();
        for (expected_idx, (name, _)) in entries.iter().enumerate() {
            let actual_idx = get_registry_entry_index("minecraft:dimension_type", name)
                .unwrap_or_else(|_| panic!("{name} should be found"));
            assert_eq!(
                actual_idx, expected_idx as i32,
                "entry {name} index mismatch"
            );
        }
    }

    #[test]
    fn test_registry_entry_index_unknown_entry() {
        let result = get_registry_entry_index("minecraft:dimension_type", "minecraft:nonexistent");
        assert!(result.is_err());
    }

    #[test]
    fn test_registry_entry_index_unknown_registry() {
        let result = get_registry_entry_index("minecraft:nonexistent", "minecraft:overworld");
        assert!(result.is_err());
    }
}
