name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: oxidized-mc/ci/.github/workflows/rust-ci.yml@main
    with:
      workspace: true
      cache-hash-file: "**/Cargo.lock"

