name: Dev Release

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

jobs:
  release:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      !contains(github.event.workflow_run.head_commit.message, 'chore: release') &&
      !contains(github.event.workflow_run.head_commit.message, 'chore(release)')
    uses: oxidized-mc/ci/.github/workflows/dev-release.yml@main
    with:
      binary-name: oxidized
      package-name: oxidized-server
      extra-files: "oxidized.toml"
    permissions:
      contents: write

